version: "3.7"

services:
  flask-main:
    restart: always
    image: boangri/rugpt3
    ports:
      - 5000:5000
    working_dir: /usr/src/app
    environment:
      PORT: 5000
    volumes:
      - ./:/usr/src/app
